### ISSUE TITLE
接收通知触发事件无法响应

### ISSUE THREAD

**Issue by cqiuping** [jpush/jpush-phonegap-plugin#301]
```
export class AppModule {
  constructor(private media:Media,
              private backgroundMode: BackgroundMode,
              public platform: Platform,
              private appMinimize: AppMinimize,
              ) {
  
    document.addEventListener('jpush.receiveNotification', (event: any) => {
      alert("haha");
    }, false);
    document.addEventListener('jpush.receiveMessage', (event:any) => {
      alert("hello");
    },false);
 
      }
    )
  }
```
我在ionic2的app.module.ts的构造器里面添加了监听代码，接收通知之后没有触发相应的事件，是什么原因呢

**Comment by lhw5123** [comment]
加在页面的 ts 里。 hev1n 邮箱：hev1n@qq.com 签名由 网易邮箱大师 定制 在2017年12月17日 22:17，soputasmile 写道： export class AppModule {
  constructor(private media:Media,
              private backgroundMode: BackgroundMode,
              public platform: Platform,
              private appMinimize: AppMinimize,
              ) {
  
    document.addEventListener('jpush.receiveNotification', (event: any) => {
      alert("haha");
    }, false);
    document.addEventListener('jpush.receiveMessage', (event:any) => {
      alert("hello");
    },false);
 
      }
    )
  }
 我在ionic2的app.module.ts的构造器里面添加了监听代码，接收通知之后没有触发相应的事件，是什么原因呢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cqiuping** [comment]
谢谢回答~
我放在home.ts里面还是不行，后来发现是我少了一句
```
window['plugins'].jPushPlugin.init();
```
加上这一句放在app.module.ts里面也是可以的
哈哈哈，再次谢谢你的秒回~
