### ISSUE TITLE
应用程序关闭后能否收到通知

### ISSUE THREAD

**Issue by xml777** [jpush/jpush-phonegap-plugin#76]
安装测试了JPush，应用程序在打开的情况下，或者在后台运行的情况下，能否收到推送，没有问题，但是在app退出进程的情况下，无法收到推送。

请问这个插件本来就是这样设计的还是bug？

**Comment by xifengzhu** [comment]
你是在ios么？
你在xcode build app的时候有没有在background model里面勾选 remote  notification？

**Comment by xml777** [comment]
ios 没问题，  android 下收不到

**Comment by darkterrorooo** [comment]
android 收不到是因为推送原理上是这样的。退出进程收不到。再次启动进程能收到。
ios 能收到是因为apple 的机制决定的。

**Comment by Alplob** [comment]
Hello,

Is there any solution for Android app on that point? I tried to use this plugin in order to prevent the app from going to sleep while in background (https://github.com/katzer/cordova-plugin-background-mode) but it seems notifications still cannot be received by the app after a while in background...

Thanks!
